---
homeassistant:
  packages:
    bootstrap: !include packages/bootstrap/config.yaml
    frontend: !include packages/frontend/config.yaml
    ground_floor: !include packages/areas/ground_floor/config.yaml
    kitchen: !include packages/areas/kitchen/config.yaml
    living_room: !include packages/areas/living_room/config.yaml
    toilet: !include packages/areas/toilet/config.yaml
    stairway: !include packages/areas/stairway/config.yaml
    bathroom: !include packages/areas/bathroom/config.yaml
    bedroom: !include packages/areas/bedroom/config.yaml
    porch: !include packages/areas/porch/config.yaml
    presence: !include packages/presence/config.yaml
    misc: !include packages/misc/config.yaml
  customize:
    media_player.living_room_ma:
      device_class: receiver
    media_player.living_room_tv:
      device_class: tv

# Let's keep these, so we can do some simple development in UI
# before we create a proper configuration via code
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homekit:
  name: Babice
  filter:
    include_entities:
      - cover.bedroom
      - cover.ground_floor
      - light.living_room_tv_leds_power
      - light.living_room_reflectors
      - light.living_room_light_standing_lamp
  entity_config:
    light.living_room_tv_leds_power:
      name: TV Leds
    light.living_room_reflectors:
      name: TV Reflectors
    light.living_room_light_standing_lamp:
      name: Standing lamp
    media_player.living_room_tv:
      name: "Bravia"
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute
    media_player.living_room_ma:
      name: "Music Assistant"
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute
