---

homeassistant:
  customize:
    cover.ground_floor:
      device_class: curtain
  packages:
    bootstrap: !include packages/bootstrap/config.yaml
    frontend: !include packages/frontend/config.yaml
    ground_floor: !include packages/areas/ground_floor/config.yaml
    vestibule: !include packages/areas/vestibule/config.yaml
    kitchen: !include packages/areas/kitchen/config.yaml
    living_room: !include packages/areas/living_room/config.yaml
    toilet: !include packages/areas/toilet/config.yaml
    stairway: !include packages/areas/stairway/config.yaml
    bathroom: !include packages/areas/bathroom/config.yaml
    bedroom: !include packages/areas/bedroom/config.yaml
    laundry_room: !include packages/areas/laundry_room/config.yaml
    boiler_room: !include packages/areas/boiler_room/config.yaml
    porch: !include packages/areas/porch/config.yaml
    terrace: !include packages/areas/terrace/config.yaml
    presence: !include packages/presence/config.yaml
    misc: !include packages/misc/config.yaml
    homekit: !include packages/homekit/config.yaml

# Lovelace dashboard configuration
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
    - url: /hacsfiles/mass-player-card/mass-player-card.js
      type: module
    - url: /local/voice-music-search-card.js
      type: module
  dashboards:
    wall-tablet:
      mode: yaml
      filename: dashboards/tablet.yaml
      title: Tablet
      icon: mdi:tablet
      show_in_sidebar: true
      require_admin: false

# Let's keep these, so we can do some simple development in UI
# before we create a proper configuration via code
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
