---

homeassistant:
  customize:
    cover.ground_floor:
      device_class: curtain
  packages:
    bootstrap: !include packages/bootstrap/config.yaml
    frontend: !include packages/frontend/config.yaml
    # Ground floor
    ground_floor: !include packages/areas/ground-floor/_floor/config.yaml
    kitchen: !include packages/areas/ground-floor/kitchen/config.yaml
    living_room: !include packages/areas/ground-floor/living-room/config.yaml
    toilet: !include packages/areas/ground-floor/toilet/config.yaml
    vestibule: !include packages/areas/ground-floor/vestibule/config.yaml
    boiler_room: !include packages/areas/ground-floor/boiler-room/config.yaml
    # First floor
    bedroom: !include packages/areas/first-floor/bedroom/config.yaml
    bathroom: !include packages/areas/first-floor/bathroom/config.yaml
    laundry: !include packages/areas/first-floor/laundry/config.yaml
    hall: !include packages/areas/first-floor/hall/config.yaml
    # Outdoor
    porch: !include packages/areas/outdoor/porch/config.yaml
    terrace: !include packages/areas/outdoor/terrace/config.yaml
    presence: !include packages/presence/config.yaml
    misc: !include packages/misc/config.yaml
    homekit: !include packages/homekit/config.yaml

# Lovelace dashboard configuration
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
    - url: /hacsfiles/mass-player-card/mass-player-card.js
      type: module
    - url: /local/voice-music-search-card.js?v=3
      type: module
  dashboards:
    wall-tablet:
      mode: yaml
      filename: dashboards/tablet.yaml
      title: Tablet
      icon: mdi:tablet
      show_in_sidebar: true
      require_admin: false

# Let's keep these, so we can do some simple development in UI
# before we create a proper configuration via code
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
