---
automation: !include_dir_list automations
media_player: !include_dir_list media_players
light: !include_dir_list lights
cover:
  - platform: group
    name: ground_floor
    entities:
      - cover.living_room_main
      - cover.living_room_left
template: !include_dir_list templates

input_boolean:
  living_room_humidification_active:
    name: Living Room Humidification Active
    initial: true
    icon: mdi:water-check
