---
automation: !include_dir_list automations
light: !include_dir_list lights
cover:
  - platform: group
    alias: Ground Floor
    name: ground_floor
    entities:
      - cover.living_room_main
      - cover.living_room_left
