---
automation: !include_dir_list automations
media_player: !include_dir_list media_players
light: !include_dir_list lights
cover:
  - platform: group
    name: ground_floor
    device_class: curtain
    entities:
      - cover.living_room_main
      - cover.living_room_left
template: !include_dir_list templates
