---
automation: !include_dir_list automations
template: !include_dir_list templates
light: !include_dir_list lights

input_boolean:
  toilet_occupied:
    name: Toilet Occupied
    initial: false
    icon: mdi:toilet
