---
automation: !include_dir_list automations

homekit:
  name: Babice
  filter:
    include_entities:
      - input_boolean.christmas_mode
      - cover.bedroom
      - cover.ground_floor
      - cover.living_room_left
      - cover.living_room_main_curtains

      # Living Room
      - light.living_room_tv_leds_with_power
      - light.living_room_reflectors
      - light.standing_lamp
      - climate.living_room

      # Dining
      - light.dining_room
      - light.ground_floor_painting_walls

      # Kitchen
      - light.kitchen_island
      - light.kitchen_glass_case
      - light.kitchen_led
      - light.kitchen_main
      # Stairway/Hall
      - light.stairway
      - light.hall_bulbs
      - light.ground_floor_hall

      # Vestibule
      - light.mudroom

      # Bathroom
      - light.bathroom_main
      - light.bathroom_ambient
      - light.bathroom_mirror

      # Toilet
      - light.toilet_main
      - light.toilet_ambient

      # Utility Rooms
      - light.boiler_room
      - light.laundry

      # Misc
      - light.terrace_wall
      - light.porch

      # Bedroom
      - humidifier.bedroom
      - light.bedroom_jakub
      - light.bedroom_sona_with_power
      - light.bedroom_leds_with_power
      - light.bedroom_main
      - light.bedroom_reflectors_with_power
      - light.bed_stripe
      - light.bedroom_wardrobe

      # Private Bathroom
      - light.ensuite_bathroom_mirror
      - light.ensuite_bathroom_leds
      - light.ensuite_bathroom_main

      - vacuum.l10_ultra

      # Cameras
      - camera.doorbell_rtsp
      - camera.porch
  entity_config:
    cover.bedroom:
      name: Curtains
    cover.ground_floor:
      name: Curtains
    cover.living_room_main_curtains:
      name: Main Curtains
    cover.living_room_left:
      name: Left Curtains

    light.living_room_tv_leds_with_power:
      name: TV Leds
    light.living_room_reflectors:
      name: TV Reflectors
    light.dining_room:
      name: Dining
    light.ground_floor_painting_walls:
      name: Walls

    light.kitchen_island:
      name: Island
    light.kitchen_glass_case:
      name: Glass case
    light.kitchen_led:
      name: Leds
    light.kitchen_main:
      name: Main

    light.stairway:
      name: Stairway
    light.hall_bulbs:
      name: Hall
    light.ground_floor_hall:
      name: Ground Hall

    light.mudroom:
      name: Mudroom

    light.bathroom_main:
      name: Main
    light.bathroom_ambient:
      name: Ambient
    light.bathroom_mirror:
      name: Mirror

    light.toilet_main:
      name: Main
    light.toilet_ambient:
      name: Ambient

    light.boiler_room:
      name: Boiler Room
    light.laundry:
      name: Laundry

    light.terrace_wall:
      name: Terrace
    light.porch:
      name: Porch

    humidifier.bedroom:
      name: Humidifier
    light.bedroom_jakub:
      name: Jacob
    light.bedroom_sona_with_power:
      name: Sonia
    light.bedroom_leds_with_power:
      name: LEDs
    light.bedroom_main:
      name: Main
    light.bedroom_reflectors_with_power:
      name: Reflectors
    light.bed_stripe:
      name: Under Bed
    light.bedroom_wardrobe:
      name: Wardrobe

    light.ensuite_bathroom_mirror:
      name: Mirror
    light.ensuite_bathroom_leds:
      name: LEDs
    light.ensuite_bathroom_main:
      name: Main

    vacuum.l10_ultra:
      name: Vacuum

    camera.doorbell_rtsp:
      name: Doorbell
      linked_doorbell_sensor: binary_sensor.doorbell_press
      video_codec: copy
      audio_codec: copy
    camera.porch:
      name: Porch Camera
      video_codec: copy
      audio_codec: copy

    input_boolean.christmas_mode:
      name: Christmas Mode
