---
homekit:
  name: Babice
  filter:
    include_entities:
      - cover.bedroom
      - cover.ground_floor

      # Living Room
      - light.living_room_tv_leds_with_power
      - light.living_room_reflectors
      - light.living_room_light_standing_lamp

      # Kitchen
      - light.kitchen_island
      - light.kitchen_glass_case
      - light.kitchen_led
      - light.kitchen_main
      # Misc
      - light.terrace_wall
      - light.porch

      # Bedroom
      - light.bedroom_jakub
      - light.bedroom_sona

      # Private Bathroom
      - light.ensuite_bathroom_mirror

      # Scripts
      - script.open_apple_tv
      - script.open_disney
      - script.open_max
      - script.open_netflix
      - script.open_prime

      - vacuum.l10_ultra
  entity_config:
    cover.bedroom:
      name: Curtains
    cover.ground_floor:
      name: Curtains

    light.living_room_tv_leds_power:
      name: TV Leds
    light.living_room_reflectors:
      name: TV Reflectors
    light.living_room_light_standing_lamp:
      name: Standing lamp

    light.kitchen_island:
      name: Island
    light.kitchen_glass_case:
      name: Glass case
    light.kitchen_led:
      name: Leds
    light.kitchen_main:
      name: Main
    light.terrace_wall:
      name: Terrace
    light.porch:
      name: Porch

    light.bedroom_jakub:
      name: Jacob
    light.bedroom_sona:
      name: Sonia

    light.ensuite_bathroom_mirror:
      name: Mirror

    vacuum.l10_ultra:
      name: Vacuum

