---
homekit:
  name: Babice
  filter:
    include_entities:
      - cover.bedroom
      - cover.ground_floor

      # Living Room
      - light.living_room_tv_leds_with_power
      - light.living_room_reflectors
      - light.living_room_light_standing_lamp

      # Dining
      - light.dining_room

      # Kitchen
      - light.kitchen_island
      - light.kitchen_glass_case
      - light.kitchen_led
      - light.kitchen_main
      # Misc
      - light.terrace_wall
      - light.porch

      # Bedroom
      - light.bedroom_jakub
      - light.bedroom_sona
      - light.bedroom_leds
      - light.bedroom_main
      - light.bedroom_reflectors

      # Private Bathroom
      - light.ensuite_bathroom_mirror
      - light.ensuite_bathroom_leds
      - light.ensuite_bathroom_main

      # Scripts
      - script.open_apple_tv
      - script.open_disney
      - script.open_max
      - script.open_netflix
      - script.open_prime
      - script.open_vod
      - script.continue_watching

      - vacuum.l10_ultra
  entity_config:
    cover.bedroom:
      name: Curtains
    cover.ground_floor:
      name: Curtains

    light.living_room_tv_leds_with_power:
      name: TV Leds
    light.living_room_reflectors:
      name: TV Reflectors
    light.living_room_light_standing_lamp:
      name: Standing lamp


    light.dining_room:
      name: Dining

    light.kitchen_island:
      name: Island
    light.kitchen_glass_case:
      name: Glass case
    light.kitchen_led:
      name: Leds
    light.kitchen_main:
      name: Main
    light.terrace_wall:
      name: Terrace
    light.porch:
      name: Porch

    light.bedroom_jakub:
      name: Jacob
    light.bedroom_sona:
      name: Sonia
    light.bedroom_leds:
      name: LEDs
    light.bedroom_main:
      name: Main
    light.bedroom_reflectors:
      name: Reflectors


    light.ensuite_bathroom_mirror:
      name: Mirror
    light.ensuite_bathroom_leds:
      name: LEDs
    light.ensuite_bathroom_main:
      name: Main

    script.open_vod:
      name: TV time
    script.open_netflix:
      name: Netflix time
    script.open_apple_tv:
      name: Apple TV time
    script.open_disney:
      name: Disney time
    script.open_max:
      name: Max time
    script.open_prime:
      name: Prime Video time

    vacuum.l10_ultra:
      name: Vacuum
