---
automation: !include_dir_list automations
light: !include_dir_list lights
template: !include_dir_list templates

input_boolean:
  bedroom_movie_mode:
    name: Bedroom Movie Mode
    initial: false
    icon: mdi:movie-open
